# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: pnpm install

    - name: Run eslint
      run: npx eslint . --ext .js,.ts

    - name: Run tests
      run: pnpm run test

    - name: Run Prettier
      run: npx prettier --write {file_path}
